name = "shopwice-api"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./public"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "shopwice_cache"
id = "2a9f8578f9754c43917b85b4f0706714"

[[d1_databases]]
binding = "DB"
database_name = "shopwice-db"
database_id = "c9a137d2-5fba-41f4-9e9c-a957787e186f"

[[r2_buckets]]
binding = "R2"
bucket_name = "shopwice-media"


[vars]
NODE_ENV = "production"
WC_URL = "https://shopwice.com"
# Add other non-secret vars here if needed.
# Secrets like WC_CONSUMER_KEY, DB_PASSWORD must be added via 'wrangler pages secret put' or the Dashboard.
